spring:
  application:
    name: kubstu-memcached
  datasource:
    url: jdbc:postgresql://localhost:5433/postgreSQL
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  output:
    ansi:
      enabled: ALWAYS

app:
  cache:
    expirationTime: 60000